LabBookingApp.Web/Controllers/BookingListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using LabBookingApp.Service.Interface;
using System.Security.Claims;

namespace LabBookingApp.Web.Controllers
{
    public class BookingListsController : Controller
    {
        private readonly IBookingListService _bookingListService;

        public BookingListsController(IBookingListService bookingListService)
        {
            _bookingListService = bookingListService;
        }

        // GET: BookingLists
        public IActionResult Index()
        {
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var dto = _bookingListService.getBookingsInfo(user);
            return View(dto);
        }

        public IActionResult DeleteFromBookingsList(Guid id)
        {
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _bookingListService.deleteBookingFromShoppingCart(user, id); 
            return RedirectToAction("Index");
        }
        public IActionResult order()
        {
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _bookingListService.order(user);
            return RedirectToAction("Index");
        }
    }
}

LabBookingApp.Web/Views/BookingLists/Create.cshtml
@model LabBookingApp.Domain.Domain.BookingList

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>BookingList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="userId" class="control-label"></label>
                <input asp-for="userId" class="form-control" />
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LabBookingApp.Web/Views/BookingLists/Delete.cshtml
@model LabBookingApp.Domain.Domain.BookingList

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookingList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LabBookingApp.Web/Views/BookingLists/Details.cshtml
@model LabBookingApp.Domain.Domain.BookingList

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>BookingList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LabBookingApp.Web/Views/BookingLists/Edit.cshtml
@model LabBookingApp.Domain.Domain.BookingList

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>BookingList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="userId" class="control-label"></label>
                <input asp-for="userId" class="form-control" />
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LabBookingApp.Web/Views/BookingLists/Index.cshtml
@model LabBookingApp.Domain.DTO.BookingListDto

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row-4">
        <a asp-controller="BookingLists" asp-action="order" class="btn btn-info">Order now</a>
    </div>

    <div class="row m-4">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Apartment Name</th>
                    <th scope="col">Price per night</th>
                    <th scope="col">Total nights</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.allReservations.Count == 0)
                {
                    <tr>
                        <td colspan="5">No active Products</td>
                    </tr>
                }
                else
                {
                    @for (int i = 0; i < Model.allReservations.Count; i++)
                    {
                        var item = Model.allReservations[i];

                        <tr>
                            <th scope="row">@(i + 1)</th>
                            <td>@item.Reservation.Apartment.ApartmentName</td>
                            <td>@item.Reservation.Apartment.Price_per_night</td>
                            <td>$@item.Number_of_nights</td>
                            <td><a asp-controller="BookingLists" asp-action="DeleteFromBookingsList" asp-route-id="@item.Id" class="btn btn-danger">Delete From ShoppingCart</a></td>
                        </tr>
                    }
                }
            </tbody>
            <tfoot class="thead-dark">
                <tr>
                    <th scope="col">TotalPrice:</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col">$@Model.totalPrice</th>
                </tr>
            </tfoot>
        </table>
    </div>

</div>